# Generated by Django 4.2.7 on 2023-12-02 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='Сумма оплаты'),
        ),
        migrations.AddField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='Сумма оплаты'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
